server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pers.gradel.ls.jdbc.entity
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sea?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&autoReconnect=true&rewriteBatchedStatements=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
